### ISSUE TITLE
err on node 8

### ISSUE THREAD

**Issue by ashleygwilliams** [ceejbot/furthermore#102]
node version 8.0.0

```
Ashleys-MacBook-Pro-2:pkg-spam-follower ag_dubs$ fm -e prod get user_acl_url
/Users/ag_dubs/.nvm/versions/node/v8.0.0/lib/node_modules/furthermore/index.js:73
		if (reply.node.dir)
		              ^

TypeError: Cannot read property 'dir' of undefined
    at etcd.get (/Users/ag_dubs/.nvm/versions/node/v8.0.0/lib/node_modules/furthermore/index.js:73:17)
    at Client._handleResponse (/Users/ag_dubs/.nvm/versions/node/v8.0.0/lib/node_modules/furthermore/node_modules/node-etcd/lib/client.js:230:14)
    at Request._callback (/Users/ag_dubs/.nvm/versions/node/v8.0.0/lib/node_modules/furthermore/node_modules/node-etcd/lib/client.js:139:22)
    at Request.self.callback (/Users/ag_dubs/.nvm/versions/node/v8.0.0/lib/node_modules/furthermore/node_modules/request/request.js:198:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/Users/ag_dubs/.nvm/versions/node/v8.0.0/lib/node_modules/furthermore/node_modules/request/request.js:1057:14)
    at emitOne (events.js:120:20)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/Users/ag_dubs/.nvm/versions/node/v8.0.0/lib/node_modules/furthermore/node_modules/request/request.js:1003:12)
```

**Comment by ashleygwilliams** [comment]
when tried on node 6 the exact same command worked perfectly
